M48
; DRILL file {KiCad 8.0.4} date 2024-12-28T01:26:13+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-28T01:26:13+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C3.500
%
G90
G05
T1
X101.462Y-145.401
T2
X130.81Y-83.439
T3
X126.31Y-83.439
T4
X84.764Y-94.984
X126.13Y-136.35
T5
X84.71Y-136.36
X126.06Y-94.91
M30
